import { useEffect, useState } from 'react'
import { CheckCircle, Warning, QrCode } from '@phosphor-icons/react'
import { supabase } from '../../lib/supabase'
import { PageHeader } from '../../components/Shell'
import { usePharmacyName } from '../../hooks/usePharmacyName'

// ── SetupMFA ──────────────────────────────────────────────────────────────────
// TOTP MFA enrollment page. Staff members enroll here to activate 2FA on their
// account. Shows the QR code to scan in an authenticator app, then verifies the
// first code to confirm enrollment.
//
// ⚠️  I-09: Requires "Multi-Factor Authentication (TOTP)" enabled in the
//     Supabase project's Authentication settings.
//
// Accessible at /profile/security — no special permission required beyond
// having an authenticated session (any staff member can enroll).

type Step = 'check' | 'already-enrolled' | 'enroll' | 'confirm' | 'done'

interface EnrollData {
  id: string
  qrCode: string   // SVG data URI returned by Supabase
  secret: string   // Manual entry fallback
}

export default function SetupMFA() {
  const pharmacyName = usePharmacyName()

  const [step, setStep]           = useState<Step>('check')
  const [enrollData, setEnrollData] = useState<EnrollData | null>(null)
  const [code, setCode]           = useState('')
  const [error, setError]         = useState<string | null>(null)
  const [loading, setLoading]     = useState(false)

  // On mount, check current enrollment status
  useEffect(() => {
    async function checkEnrollment() {
      const { data: factors } = await supabase.auth.mfa.listFactors()
      const enrolled = factors?.totp.find(f => f.status === 'verified')
      setStep(enrolled ? 'already-enrolled' : 'enroll')
    }
    void checkEnrollment()
  }, [])

  async function startEnrollment() {
    setLoading(true)
    setError(null)
    const { data, error: enrollErr } = await supabase.auth.mfa.enroll({
      factorType: 'totp',
      issuer: `PharmacyOS — ${pharmacyName}`,
      // friendlyName autogenerated; user can change in authenticator app
    })
    setLoading(false)
    if (enrollErr || !data) {
      setError(enrollErr?.message ?? 'Could not start enrollment.')
      return
    }
    setEnrollData({
      id:      data.id,
      qrCode:  data.totp.qr_code,
      secret:  data.totp.secret,
    })
    setStep('confirm')
  }

  async function confirmEnrollment(e: React.FormEvent) {
    e.preventDefault()
    if (!enrollData) return
    setLoading(true)
    setError(null)

    const { data: challenge, error: challengeErr } =
      await supabase.auth.mfa.challenge({ factorId: enrollData.id })
    if (challengeErr || !challenge) {
      setError(challengeErr?.message ?? 'Challenge failed.')
      setLoading(false)
      return
    }

    const { error: verifyErr } = await supabase.auth.mfa.verify({
      factorId:    enrollData.id,
      challengeId: challenge.id,
      code:        code.trim(),
    })
    setLoading(false)
    if (verifyErr) {
      setError('Incorrect code — check your authenticator app and try again.')
    } else {
      setStep('done')
    }
  }

  async function unenroll() {
    setLoading(true)
    setError(null)
    const { data: factors } = await supabase.auth.mfa.listFactors()
    const enrolled = factors?.totp.find(f => f.status === 'verified')
    if (enrolled) {
      const { error: unenrollErr } = await supabase.auth.mfa.unenroll({ factorId: enrolled.id })
      if (unenrollErr) {
        setError(unenrollErr.message)
        setLoading(false)
        return
      }
    }
    setLoading(false)
    setStep('enroll')
  }

  return (
    <div>
      <PageHeader
        title="Two-Factor Authentication"
        subtitle="Protect your account with a TOTP authenticator app"
        breadcrumb={['Profile', 'Security']}
      />

      <div className="max-w-lg">

        {/* ── Already enrolled ─────────────────────────────────────────── */}
        {step === 'already-enrolled' && (
          <div className="card p-6">
            <div className="flex items-start gap-3 bg-emerald-50 border border-emerald-200 rounded-lg px-4 py-3 mb-6">
              <CheckCircle size={18} weight="duotone" className="text-emerald-600 shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-semibold text-emerald-800">Two-factor authentication is active</p>
                <p className="text-xs text-emerald-700 mt-0.5">
                  Your account is protected. You will be prompted for a code on each login.
                </p>
              </div>
            </div>
            <p className="text-xs text-gray-500 mb-4">
              To change your authenticator app, remove the current factor and re-enroll.
              You will need to complete a verification step on your next login.
            </p>
            <button
              onClick={unenroll}
              disabled={loading}
              className="btn btn-ghost text-red-600 hover:bg-red-50 gap-1.5 text-xs border border-red-200"
            >
              {loading ? 'Removing…' : 'Remove 2FA'}
            </button>
            {error && (
              <p role="alert" className="mt-3 text-xs text-red-600">{error}</p>
            )}
          </div>
        )}

        {/* ── Start enrollment ─────────────────────────────────────────── */}
        {step === 'enroll' && (
          <div className="card p-6">
            <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-lg px-4 py-3 mb-6">
              <Warning size={18} weight="duotone" className="text-amber-600 shrink-0 mt-0.5" />
              <p className="text-sm text-amber-800">
                Two-factor authentication is <strong>not enabled</strong> on your account.
                We recommend all staff enable 2FA.
              </p>
            </div>
            <p className="text-sm text-gray-600 mb-4">
              You will need an authenticator app such as Google Authenticator, Authy, or 1Password
              to complete setup.
            </p>
            <button
              onClick={startEnrollment}
              disabled={loading}
              className="btn btn-primary gap-1.5"
            >
              <QrCode size={14} />
              {loading ? 'Setting up…' : 'Set Up Authenticator'}
            </button>
            {error && (
              <p role="alert" className="mt-3 text-xs text-red-600">{error}</p>
            )}
          </div>
        )}

        {/* ── QR code + confirm ────────────────────────────────────────── */}
        {step === 'confirm' && enrollData && (
          <div className="card p-6">
            <h2 className="font-semibold text-gray-800 mb-1">Scan QR Code</h2>
            <p className="text-xs text-gray-500 mb-4">
              Open your authenticator app, tap <strong>Add account</strong>, and scan the code below.
            </p>

            {/* QR code — Supabase returns an SVG as a data URI */}
            <div className="flex justify-center mb-4">
              <img
                src={enrollData.qrCode}
                alt="QR code for PharmacyOS authenticator enrollment"
                className="w-48 h-48 border border-gray-200 rounded-lg"
              />
            </div>

            {/* Manual entry fallback */}
            <details className="text-xs text-gray-500 mb-6">
              <summary className="cursor-pointer hover:text-gray-800 transition-colors">
                Can't scan? Enter setup key manually
              </summary>
              <code className="block mt-2 bg-gray-50 border border-gray-200 rounded px-3 py-2 font-mono text-xs break-all text-gray-700">
                {enrollData.secret}
              </code>
            </details>

            <form onSubmit={confirmEnrollment} className="space-y-4">
              <div>
                <label
                  htmlFor="setup-code"
                  className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5"
                >
                  Enter the 6-digit code to confirm
                </label>
                <input
                  id="setup-code"
                  type="text"
                  inputMode="numeric"
                  pattern="\d{6}"
                  maxLength={6}
                  required
                  autoFocus
                  autoComplete="one-time-code"
                  value={code}
                  onChange={e => {
                    setCode(e.target.value.replace(/\D/g, ''))
                    if (error) setError(null)
                  }}
                  className={`input text-center text-lg tracking-[0.5em] font-mono ${
                    error ? 'border-red-400 focus:ring-red-300' : ''
                  }`}
                  placeholder="000000"
                  aria-describedby={error ? 'setup-code-error' : undefined}
                />
                {error && (
                  <p id="setup-code-error" role="alert" className="mt-1.5 text-xs text-red-600">
                    {error}
                  </p>
                )}
              </div>

              <button
                type="submit"
                disabled={loading || code.length !== 6}
                className="btn btn-primary w-full justify-center"
              >
                {loading
                  ? <span className="inline-block w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" aria-hidden="true" />
                  : 'Confirm & Activate 2FA'}
              </button>
            </form>
          </div>
        )}

        {/* ── Done ─────────────────────────────────────────────────────── */}
        {step === 'done' && (
          <div className="card p-6">
            <div className="flex items-start gap-3 bg-emerald-50 border border-emerald-200 rounded-lg px-4 py-3">
              <CheckCircle size={18} weight="duotone" className="text-emerald-600 shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-semibold text-emerald-800">
                  Two-factor authentication activated
                </p>
                <p className="text-xs text-emerald-700 mt-0.5">
                  Your account is now protected. You will be prompted for a verification
                  code on your next login.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Fallback for 'check' loading state */}
        {step === 'check' && (
          <div className="card p-6 flex items-center justify-center h-32">
            <span className="w-6 h-6 border-2 border-blue-600 border-t-transparent rounded-full animate-spin" aria-hidden="true" />
          </div>
        )}
      </div>
    </div>
  )
}
