// ReportAssistant — AI Q&A panel for report pages
// Drop this at the bottom of any report page and supply a data_summary string
// (compact text representation of the current report's data) and a report_type label.
// Requires the `report-assistant` Supabase Edge Function and ANTHROPIC_API_KEY secret.

import { useState } from 'react'
import { Sparkle, PaperPlaneTilt, CaretDown, CaretUp, Warning } from '@phosphor-icons/react'
import { supabase } from '../lib/supabase'

interface Props {
  /** Compact text description of the current report data — passed to Claude as context. */
  dataSummary: string
  /** Label shown in the prompt placeholder and Edge Function request, e.g. "Revenue", "Inventory". */
  reportType: string
}

type AnswerState =
  | { status: 'idle' }
  | { status: 'loading' }
  | { status: 'success'; text: string }
  | { status: 'error'; message: string }

export function ReportAssistant({ dataSummary, reportType }: Props) {
  const [open, setOpen]       = useState(false)
  const [question, setQuestion] = useState('')
  const [answer, setAnswer]   = useState<AnswerState>({ status: 'idle' })

  async function ask() {
    const q = question.trim()
    if (!q || answer.status === 'loading') return

    setAnswer({ status: 'loading' })
    try {
      const { data, error } = await supabase.functions.invoke('report-assistant', {
        body: { question: q, data_summary: dataSummary, report_type: reportType },
      })
      if (error) throw error
      if (data?.error) throw new Error(data.error)
      setAnswer({ status: 'success', text: data.answer })
    } catch (err) {
      const msg = String((err as Error).message ?? err)
      setAnswer({
        status: 'error',
        message: msg.includes('ANTHROPIC_API_KEY')
          ? 'AI assistant is not yet configured. Set ANTHROPIC_API_KEY in Supabase project secrets.'
          : msg,
      })
    }
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      ask()
    }
  }

  return (
    <section className="mt-6" aria-label="Report AI assistant">
      {/* Toggle button */}
      <button
        onClick={() => setOpen(o => !o)}
        className="flex items-center gap-2 text-xs text-indigo-600 hover:text-indigo-800 font-medium transition-colors"
        aria-expanded={open}
      >
        <Sparkle size={14} weight="fill" aria-hidden="true" />
        Ask the Report Assistant
        {open
          ? <CaretUp size={12} aria-hidden="true" />
          : <CaretDown size={12} aria-hidden="true" />
        }
      </button>

      {open && (
        <div className="mt-3 rounded-lg border border-indigo-100 bg-indigo-50 p-4">
          <p className="text-xs text-indigo-600 mb-3">
            Ask a question about the <strong>{reportType}</strong> data currently loaded in this report.
            The assistant only has access to what is shown — it cannot access other periods or historical records.
          </p>

          {/* Input row */}
          <div className="flex gap-2">
            <input
              type="text"
              value={question}
              onChange={e => setQuestion(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder={`e.g. "Which product had the highest velocity this period?"`}
              className="flex-1 input text-sm"
              aria-label={`Ask a question about the ${reportType} report`}
              disabled={answer.status === 'loading'}
            />
            <button
              onClick={ask}
              disabled={!question.trim() || answer.status === 'loading'}
              className="btn btn-primary flex items-center gap-1.5 px-3 py-2 text-xs"
              aria-label="Submit question to AI assistant"
            >
              <PaperPlaneTilt size={14} aria-hidden="true" />
              {answer.status === 'loading' ? 'Thinking…' : 'Ask'}
            </button>
          </div>

          {/* Answer */}
          {answer.status === 'success' && (
            <div className="mt-3 p-3 rounded bg-white border border-indigo-100 text-sm text-gray-700 leading-relaxed">
              {answer.text}
              <p className="mt-2 text-xs text-gray-400">
                Generated by Claude Haiku based on data visible in this report. Verify against source records before acting.
              </p>
            </div>
          )}

          {answer.status === 'error' && (
            <div className="mt-3 flex items-start gap-2 p-3 rounded bg-amber-50 border border-amber-200">
              <Warning size={14} className="text-amber-600 mt-0.5 shrink-0" aria-hidden="true" />
              <p className="text-xs text-amber-800">{answer.message}</p>
            </div>
          )}

          {answer.status === 'loading' && (
            <div className="mt-3 text-xs text-indigo-500 animate-pulse">
              Analysing report data…
            </div>
          )}
        </div>
      )}
    </section>
  )
}
